### ISSUE TITLE
Would multFlag=False ensure performance gain?

### ISSUE THREAD

**Issue by zhaohui-yang** [shamangary/Pytorch-Stochastic-Depth-Resnet#1]
Thank you for sharing this great repo!

I have reimplemented this method and found the accuracy degrades for the model trained on the ImageNet. This conclusion is some kind of similar to yours' 'multiFlag=True'. 

And I wonder if your settings 'multiFlag=Flag' would ensure improve the performance?

Thanks.

**Comment by shamangary** [comment]
Hello @zhaohui-yang,

Unfortunately, I didn't test the ImageNet results due to the fact that I didn't have the resource. It was tested in a much smaller set which does not make sure the performance of ImageNet.

**Comment by zhaohui-yang** [comment]
Sorry for misleading. I mean will the perforamnce increase on small dataset if the multiFlag=False? If this is not sure, I would give up continue trying this on ImageNet.

**Comment by shamangary** [comment]
My case was very specific so I am not sure :)

**Comment by zhaohui-yang** [comment]
Thanks, bro.
